name: Deploy Azure Function
on:
  push:
    branches: [ master ]
#    paths:
#      - 'serverless/cloud_wrapper/azure/cart_handler.py'
#      - 'serverless/cart_actions/**'
#      - 'serverless/db_layer/**'

jobs:
  build-func-app:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest

      - name: Create Zip Artifact
        run: |
          mkdir staging
          mkdir staging/serverless
          mkdir staging/serverless/cart_actions
          mkdir staging/serverless/db_layer
          
          cp serverless/cloud_wrapper/azure/host.json staging/
          
          cp serverless/cloud_wrapper/azure/* staging/
          cp -r serverless/cart_actions staging/serverless/
          cp serverless/__init__.py staging/serverless/

          cp serverless/db_layer/*.py staging/serverless/db_layer/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: function
          path: staging/
          retention-days: 1

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Flex Consumption
        uses: Azure/functions-action@v1
        with:
          app-name: 'cart-function'
          package: staging/

      #      - name: Trigger AzDO Pipeline
      #        uses: Azure/pipelines@v1
      #        with:
      #          azure-devops-project-url: '${{ secrets.AZURE_DEVOPS_URL }}'
      #          azure-pipeline-name: 'Cart-Function-Deploy'
      #          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
