name: Deploy Azure Function
on:
  push:
    branches: [ master ]
#    paths:
#      - 'serverless/cloud_wrapper/azure/cart_handler.py'
#      - 'serverless/cart_actions/**'
#      - 'serverless/db_layer/**'

jobs:
  build-func-app:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cosmos --target=".python_packages/lib/site-packages"

      - name: Create Zip Artifact
        run: |
          mkdir staging
          mkdir staging/serverless
          mkdir staging/serverless/cart_actions
          mkdir staging/serverless/db_layer
          
          cp -r .python_packages staging/
          cp serverless/cloud_wrapper/azure/host.json staging/
          
          cp serverless/cloud_wrapper/azure/cart_handler.py staging/
          cp serverless/cloud_wrapper/azure/__init__.py staging/

          cp -r serverless/cart_actions staging/serverless/
          cp serverless/__init__.py staging/serverless/

          cp serverless/db_layer/*.py staging/serverless/db_layer/

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: function.zip
          path: staging/
          retention-days: 1

      - name: Deploy to Flex Consumption
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az functionapp deployment source config-zip \
              -g serverless_rg \
              -n cart-function \
              --src function.zip
