name: Deploy Azure Function
on:
  push:
    branches: [ master ]
#    paths:
#      - 'serverless/cloud_wrapper/azure/cart_handler.py'
#      - 'serverless/cart_actions/**'
#      - 'serverless/db_layer/**'

jobs:
  build-func-app:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest

      - name: Create zip artifact
        run: |
          mkdir staging
          mkdir staging/serverless
          mkdir staging/serverless/cart_actions
          mkdir staging/serverless/db_layer
          
          cp serverless/cloud_wrapper/azure/* staging/
          cp serverless/__init__.py staging/serverless/
          cp serverless/cart_actions/cart_actions.py staging/serverless/cart_actions/
          cp serverless/cart_actions/process_cart_action.py staging/serverless/cart_actions/
          cp serverless/cart_actions/__init__.py staging/serverless/cart_actions/
          cp serverless/db_layer/*.py staging/serverless/db_layer/
          
          cd staging
          zip -r function.zip *

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob Storage
        run: |
          az storage blob upload \
            --account-name cartfunccode2026 \
            --container-name function-releases \
            --name function.zip \
            --file staging/function.zip \
            --overwrite true \
            --auth-mode login

      - name: Trigger AzDO Pipeline via CLI
        run: |
          # Set the PAT for the CLI to use
          echo "${{ secrets.AZURE_DEVOPS_TOKEN }}" | az devops login --organization https://dev.azure.com/valluvam

          # Trigger the pipeline
          az pipelines build queue \
            --organization https://dev.azure.com/valluvam \
            --project serverless-cart \
            --definition-name 'Cart-Function-Deploy'
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
